// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/commands/runningconfig/runningconfig.go
//
// Generated by this command:
//
//	mockgen -package=mockrunningconfig -source=pkg/commands/runningconfig/runningconfig.go -destination=./mocks/runningconfig/runningconfig.go
//

// Package mockrunningconfig is a generated GoMock package.
package mockrunningconfig

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/sdcio/config-server/apis/config/v1alpha1"
	client "github.com/sdcio/kubectl-sdc/pkg/client"
	gomock "go.uber.org/mock/gomock"
)

// MockDataClient is a mock of DataClient interface.
type MockDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockDataClientMockRecorder
	isgomock struct{}
}

// MockDataClientMockRecorder is the mock recorder for MockDataClient.
type MockDataClientMockRecorder struct {
	mock *MockDataClient
}

// NewMockDataClient creates a new mock instance.
func NewMockDataClient(ctrl *gomock.Controller) *MockDataClient {
	mock := &MockDataClient{ctrl: ctrl}
	mock.recorder = &MockDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataClient) EXPECT() *MockDataClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDataClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDataClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDataClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockDataClient) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDataClientMockRecorder) Connect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDataClient)(nil).Connect), ctx)
}

// GetIntent mocks base method.
func (m *MockDataClient) GetIntent(ctx context.Context, format client.Format, datastoreName, intentName string) (client.Intent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntent", ctx, format, datastoreName, intentName)
	ret0, _ := ret[0].(client.Intent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntent indicates an expected call of GetIntent.
func (mr *MockDataClientMockRecorder) GetIntent(ctx, format, datastoreName, intentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntent", reflect.TypeOf((*MockDataClient)(nil).GetIntent), ctx, format, datastoreName, intentName)
}

// MockRunningConfigClient is a mock of RunningConfigClient interface.
type MockRunningConfigClient struct {
	ctrl     *gomock.Controller
	recorder *MockRunningConfigClientMockRecorder
	isgomock struct{}
}

// MockRunningConfigClientMockRecorder is the mock recorder for MockRunningConfigClient.
type MockRunningConfigClientMockRecorder struct {
	mock *MockRunningConfigClient
}

// NewMockRunningConfigClient creates a new mock instance.
func NewMockRunningConfigClient(ctrl *gomock.Controller) *MockRunningConfigClient {
	mock := &MockRunningConfigClient{ctrl: ctrl}
	mock.recorder = &MockRunningConfigClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunningConfigClient) EXPECT() *MockRunningConfigClientMockRecorder {
	return m.recorder
}

// GetRunningConfig mocks base method.
func (m *MockRunningConfigClient) GetRunningConfig(ctx context.Context, namespace, name string, format client.Format) (*v1alpha1.TargetRunningConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningConfig", ctx, namespace, name, format)
	ret0, _ := ret[0].(*v1alpha1.TargetRunningConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunningConfig indicates an expected call of GetRunningConfig.
func (mr *MockRunningConfigClientMockRecorder) GetRunningConfig(ctx, namespace, name, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningConfig", reflect.TypeOf((*MockRunningConfigClient)(nil).GetRunningConfig), ctx, namespace, name, format)
}
